language: php

php:
  # Anduril uses 5.3
  - 5.3
  - 5.4
  # Dev on 5.5
  - 5.5

sudo: required

env:
  - DB=mysql

before_install:
  - cp private/.default-config.php private/.config.php
  # default coffee credentials;
  # uses user 'travis' with empty password
  - mysql -e "CREATE DATABASE coffee"

install:
  ## phpCAS
  - (cd ..; wget http://downloads.jasig.org/cas-clients/php/current.tgz; tar -xf current.tgz)

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f ci/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # Package needed by phpCAS
  - sudo apt-get install php5-curl

  # phpcs, jshint, and jscs for error/style guideline checking
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install jscs
  - npm install jshint

script: "./ci/ci-tests.sh"
